services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - API_PROTOCOL=http
      - API_HOST=fees-calculator-service:8080
      - API_VERSION=v1
    env_file:
      - .env
    networks:
      - laa

  fees-service:
    image: wiremock/wiremock:3.12.1
    container_name: fees-calculator-service
    entrypoint:
      [
        "/docker-entrypoint.sh",
        "--global-response-templating",
        "--disable-gzip",
        "--verbose",
      ]
    volumes:
      - ./wiremock/mappings/fees-service:/home/wiremock/mappings
    restart: always
    ports:
      - "8080:8080"
    networks:
      - laa

networks:
  laa:
